# Generated by Django 4.2.30 on 2026-04-17 16:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('part', models.CharField(choices=[('chest', '胸'), ('back', '背中'), ('legs', '脚'), ('shoulders', '肩'), ('arms', '腕'), ('abs', '腹筋+有酸素')], max_length=20, verbose_name='部位')),
                ('duration_min', models.IntegerField(blank=True, null=True, verbose_name='所要時間(分)')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'トレーニングセッション',
                'verbose_name_plural': 'トレーニングセッション',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.FloatField(blank=True, null=True, verbose_name='身長(cm)')),
                ('start_date', models.DateField(default='2026-04-07', verbose_name='開始日')),
                ('target_date', models.DateField(default='2026-09-03', verbose_name='目標日')),
                ('equip_settings', models.JSONField(blank=True, default=dict, verbose_name='器具設定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='種目名')),
                ('set_number', models.IntegerField(default=1, verbose_name='セット番号')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(kg)')),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='回数')),
                ('rpe', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE(主観的運動強度)')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '種目記録',
                'verbose_name_plural': '種目記録',
                'ordering': ['-date', 'exercise_name', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='計測日')),
                ('weight_kg', models.FloatField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='体重(kg)')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '体重記録',
                'verbose_name_plural': '体重記録',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompletedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='完了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '完了日',
                'verbose_name_plural': '完了日',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
